### PR TITLE
SEARCH-996 Upgrade cxf-rt-transports-http.

### PR DESCRIPTION
**Pull request by tpage-alfresco**
Whitesource identified a vulnerability in cxf-rt-transports-http 3.0.10 which
is fixed in 3.0.12. Upgrade chemistry-opencmis-serverbindings to address this
issue.

### CODE REVIEW

**Comment by derekhulley** [comment]
Upgrading CMIS to get a minor library upgrade is not how we should be doing this.
That dependency should be explicitly declared in the pom so that the version we get from CMIS is upgraded without upgrading CMIS.

**Review by derekhulley — CHANGES_REQUESTED** [review]
See previous comment.
The same goes for the final Insight Engine (or whatever).  Don't use the transitive chain to determine the libraries used; pull in what you need explicitly.

**Comment by tpage-alfresco** [comment]
I disagree with this approach. However if you don't want to update your library then we can work around it as you suggest.

**Comment by michaelsuzukisagi** [comment]
@derekhulley if possible could you elaborate why we should not upgrade to the CMIS library with the fix.
Its not a major version upgrade and we are duplicating work by changing the pom in the projects that depend on the data model.

**Comment by derekhulley** [comment]
@michaelsuzukisagi 
It is not duplication of work - quite the opposite: you want to upgrade a small library in an inconsequential way but have chosen to upgrade CMIS up a revision (1.0.0 to 1.1.0).  The work involved in testing a CMIS upgrade is excessive as the side effects of that are unknown.

The approach of making only the change you want seems reasonable to me: forcing an upgrade of a customer-facing API component as a biproduct of a security patch is too much.

**Pull request closed without merging**
