### PR TITLE
[ MNT-19577 ] FTS Grammar update + ANTLR artifacts + Unit test

### PR DESCRIPTION
**Pull request by agazzarini**
The patch addresses the MNT-19577 (property name starting with a number) by 

- updating the FTS grammar
- replacing the FTSLexer and FTSParser 
- updating the fts_test.gunit for the inclusion of the scenario depicted in the issue

### CODE REVIEW

**Comment by tpage-alfresco** [comment]
As discussed on the ticket I think we should allow searching using properties with single digit names.

**Comment by tpage-alfresco** [comment]
As discussed in the ticket we're now allowing ids that start with digits as long as they also contain an alphabetic character or an underscore. This means that it is still easy for us to discern between ids and numbers in the grammar.

**Review by tpage-alfresco — COMMENTED** [review]
This obviously looks good to me now.  @agazzarini What do you think?

**Comment by agazzarini** [comment]
I think the "compromise" is actually very good! The ID definition is shorter and clear, and it covers a wide range of scenarios.

**Pull request merged**
